export const GENERIC_REPO_INJECTION_TOKEN = Symbol(
  'GENERIC_REPO_INJECTION_TOKEN',
);
export const NOTES_SERVICE_INJECTION_TOKEN = Symbol(
  'NOTES_SERVICE_INJECTION_TOKEN',
);
export const NOTES_REPO_INJECTION_TOKEN = Symbol('NOTES_REPO_INJECTION_TOKEN');
